"""Demand Intelligence policy, vocabulary, and version ownership."""

from typing import Final

DEMAND_ANALYZER_VERSION: Final = "demand-analyzer-4"
DEMAND_FORMULA_VERSION: Final = "demand-priority-1"
DEMAND_RULE_VERSION: Final = "demand-rules-4"

DEMAND_SIGNAL_HIGH_IMPRESSION_LOW_CTR: Final = "high_impression_low_ctr"
DEMAND_SIGNAL_BRANDED_QUERY: Final = "branded_query_performance"
DEMAND_SIGNAL_STRIKING_DISTANCE: Final = "striking_distance"
DEMAND_SIGNAL_CANNIBALIZATION: Final = "query_cannibalization"
DEMAND_SIGNAL_CTR_GAP: Final = "property_relative_ctr_gap"
DEMAND_SIGNAL_EMERGING_QUERY: Final = "emerging_query"
DEMAND_SIGNAL_DECLINING_QUERY: Final = "declining_query"
DEMAND_SIGNAL_TYPES: Final[frozenset[str]] = frozenset(
    {
        DEMAND_SIGNAL_HIGH_IMPRESSION_LOW_CTR,
        DEMAND_SIGNAL_BRANDED_QUERY,
        DEMAND_SIGNAL_STRIKING_DISTANCE,
        DEMAND_SIGNAL_CANNIBALIZATION,
        DEMAND_SIGNAL_CTR_GAP,
        DEMAND_SIGNAL_EMERGING_QUERY,
        DEMAND_SIGNAL_DECLINING_QUERY,
    }
)
DEMAND_OPPORTUNITY_SIGNAL_TYPES: Final[frozenset[str]] = frozenset(
    {
        DEMAND_SIGNAL_HIGH_IMPRESSION_LOW_CTR,
        DEMAND_SIGNAL_STRIKING_DISTANCE,
        DEMAND_SIGNAL_CANNIBALIZATION,
        DEMAND_SIGNAL_CTR_GAP,
        DEMAND_SIGNAL_EMERGING_QUERY,
        DEMAND_SIGNAL_DECLINING_QUERY,
    }
)

DEMAND_SIGNAL_STATE_ACTIVE: Final = "active"
DEMAND_SIGNAL_STATE_RESOLVED: Final = "resolved"

DEMAND_MIN_IMPRESSIONS: Final = 10
DEMAND_LOW_CTR_THRESHOLD: Final = 0.02
DEMAND_SEARCH_GAP_WEIGHT: Final = 1.0
DEMAND_STRIKING_DISTANCE_MIN_IMPRESSIONS: Final = 50
DEMAND_STRIKING_DISTANCE_MIN_POSITION: Final = 4.0
DEMAND_STRIKING_DISTANCE_MAX_POSITION: Final = 15.0
DEMAND_STRIKING_DISTANCE_GAP_WEIGHT: Final = 1.25
DEMAND_CANNIBALIZATION_MIN_PAGE_IMPRESSIONS: Final = 20
DEMAND_CANNIBALIZATION_MIN_PAGE_SHARE: Final = 0.10
DEMAND_CANNIBALIZATION_GAP_WEIGHT: Final = 1.35
DEMAND_CTR_GAP_MIN_COHORT_ROWS: Final = 20
DEMAND_CTR_GAP_MIN_COHORT_IMPRESSIONS: Final = 500
DEMAND_CTR_GAP_MIN_CANDIDATE_IMPRESSIONS: Final = 100
DEMAND_CTR_GAP_RELATIVE_THRESHOLD: Final = 0.25
DEMAND_CTR_GAP_ABSOLUTE_THRESHOLD: Final = 0.02
DEMAND_CTR_GAP_WEIGHT: Final = 1.4
DEMAND_TREND_WINDOW_DAYS: Final = 14
DEMAND_TREND_REQUIRED_DAYS: Final = 28
DEMAND_TREND_MIN_TOTAL_IMPRESSIONS: Final = 50
DEMAND_TREND_MIN_WINDOW_IMPRESSIONS: Final = 10
DEMAND_TREND_EMERGING_RATIO: Final = 1.5
DEMAND_TREND_DECLINING_RATIO: Final = 0.67
DEMAND_TREND_MIN_ABSOLUTE_CHANGE: Final = 20
DEMAND_TREND_GAP_WEIGHT: Final = 1.1
DEMAND_LIST_MAX_LIMIT: Final = 200

QUERY_EVIDENCE_ANALYZER_VERSION: Final = "query-evidence-1"
QUERY_EVIDENCE_DEFAULT_LIMIT: Final = 100
QUERY_EVIDENCE_MAX_LIMIT: Final = 500
QUERY_EVIDENCE_MAX_ROWS: Final = 5000
QUERY_EVIDENCE_MAX_ARTIFACTS: Final = 100
QUERY_EVIDENCE_STATE_AVAILABLE: Final = "available"
QUERY_EVIDENCE_STATE_OBSERVED_ZERO: Final = "observed_zero"
QUERY_EVIDENCE_STATE_UNAVAILABLE: Final = "unavailable"

# Cross-source owned-page equivalence is deliberately separate from crawler
# identity. Bump whenever evidence precedence or candidate construction changes.
PAGE_EQUIVALENCE_RESOLVER_VERSION: Final = "owned-page-resolver-1"
PAGE_EQUIVALENCE_MAX_CANDIDATES: Final = 16
PAGE_EQUIVALENCE_MAX_ARTIFACTS: Final = 1000

BRANDED_QUERY_CLASSIFIER_VERSION: Final = "branded-query-1"
BRANDED_QUERY_CLASSES: Final[frozenset[str]] = frozenset(
    {"branded", "non_branded", "ambiguous"}
)
