"""Versioned crawl-scoped internal-link graph limits and thresholds."""

from typing import Final

LINK_GRAPH_ANALYZER_VERSION: Final = "link-graph-v1"
LINK_GRAPH_STATE_AVAILABLE: Final = "available"
LINK_GRAPH_STATE_INCOMPLETE: Final = "incomplete"
LINK_GRAPH_STATE_UNAVAILABLE: Final = "unavailable"
LINK_GRAPH_PAGERANK_DAMPING: Final = 0.85
LINK_GRAPH_PAGERANK_TOLERANCE: Final = 1e-8
LINK_GRAPH_PAGERANK_MAX_ITERATIONS: Final = 100
LINK_GRAPH_NEAR_ORPHAN_MAX_INBOUND: Final = 1
LINK_GRAPH_WEAK_AUTHORITY_MIN_NODES: Final = 20
LINK_GRAPH_OVER_LINKED_MIN_TARGETS: Final = 100
LINK_GRAPH_HUB_MIN_TARGETS: Final = 10
LINK_GRAPH_HUB_MAX_DEPTH: Final = 2
LINK_GRAPH_SUGGESTION_MIN_JACCARD: Final = 0.20
LINK_GRAPH_MAX_SUGGESTIONS: Final = 3
LINK_GRAPH_MAX_ANCHOR_TEXTS_PER_EDGE: Final = 5
LINK_GRAPH_ANCHOR_TEXT_MAX_LENGTH: Final = 256
LINK_GRAPH_NODE_TITLE_MAX_LENGTH: Final = 1024
LINK_GRAPH_MAX_ANCHOR_DISTRIBUTION: Final = 25
LINK_GRAPH_TOP_FRACTION: Final = 0.10
LINK_GRAPH_AUTHORITY_CONCENTRATION_THRESHOLD: Final = 0.50
LINK_GRAPH_MAX_NODES: Final = 10_000
LINK_GRAPH_MAX_REFERENCES: Final = 100_000
LINK_GRAPH_LIST_DEFAULT_LIMIT: Final = 50
LINK_GRAPH_LIST_MAX_LIMIT: Final = 200
