"""Golden onboarding cases whose buyer subscribes to software or hires a TEAM.

SaaS, regulated finance, and the local and professional services whose sites
advertise the categories they work IN -- the read the research model most
often gets wrong. See :mod:`app.evaluations.onboarding_cases_commerce` for
the other half and :mod:`app.evaluations.onboarding_corpus` for the schema.
"""

from __future__ import annotations

from app.evaluations.onboarding_corpus import GoldenOnboardingCase

_FEEDONOMICS = GoldenOnboardingCase(
    slug="feedonomics-united-states",
    brand_name="Feedonomics",
    primary_market="United States",
    website_url="https://feedonomics.com",
    sector="Software",
    category="product feed management and marketplace syndication platform",
    category_aliases=(
        "feed management software",
        "product data syndication",
        "shopping feed tool",
        "feed optimization platform",
        "product feed management",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "list products on many marketplaces at once",
        "fix merchant centre disapprovals at scale",
        "optimise product data for shopping ads",
        "keep catalog data in sync across channels",
    ),
    category_terms=(
        "product feed management",
        "marketplace integrations",
        "catalog optimization",
        "google shopping feeds",
        "product data syndication",
        "feed automation",
    ),
    expected_competitors=(
        "Productsup",
        "Channable",
        "DataFeedWatch",
        "GoDataFeed",
        "Rithum",
        "Lengow",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best product feed management software for ecommerce",
        "how to sync shopify catalog to google shopping and amazon",
        "product feed management tools compared",
        "how do i fix google merchant center disapprovals at scale",
        "best way to list products on multiple marketplaces automatically",
        "product feed optimization tools for large catalogs",
        "software to manage product data across amazon walmart ebay",
        "enterprise feed management platform pricing",
        "how to automate product feeds for shopping ads",
        "tools that handle marketplace integrations for retailers",
        "what is a product feed management platform",
        "best feed tool for agencies managing multiple clients",
    ),
    gold_branded_prompts=(
        "feedonomics vs channable",
        "is feedonomics worth the price",
        "feedonomics alternatives",
        "feedonomics vs productsup for enterprise",
        "does feedonomics support walmart marketplace",
    ),
    products_or_services=(
        "product feed management",
        "marketplace integrations",
        "catalog optimization",
    ),
    use_cases=("sell on marketplaces", "shopping ads", "manage product data"),
    market_terms=("united states", "u.s.", "us market", "usa"),
)


_CANVA = GoldenOnboardingCase(
    slug="canva-australia",
    brand_name="Canva",
    primary_market="Australia",
    website_url="https://www.canva.com",
    sector="Software",
    category="browser-based graphic design and presentation tool",
    category_aliases=(
        "graphic design tool",
        "design software",
        "presentation maker",
        "social media design app",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="both",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "make professional-looking designs without design skills",
        "produce social media content quickly",
        "keep a team on-brand with shared templates",
        "build a presentation that looks good",
    ),
    category_terms=(
        "graphic design",
        "presentation design",
        "social media graphics",
        "brand templates",
        "logo design",
        "marketing collateral",
    ),
    expected_competitors=(
        "Adobe Express",
        "Microsoft Designer",
        "VistaCreate",
        "Figma",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "easiest graphic design tool for non designers",
        "best free tool to make social media posts",
        "how to make a presentation look professional without design skills",
        "best design app for small business marketing",
        "free alternative to photoshop for simple designs",
        "tool for making instagram posts with templates",
        "best software for shared team brand templates",
        "how to create a logo without hiring a designer",
        "design tool that works in the browser with no install",
        "best app for making flyers and posters",
        "cheap design software for nonprofits",
        "collaborative design tool for marketing teams",
    ),
    gold_branded_prompts=(
        "is canva pro worth it",
        "canva vs adobe express",
        "canva vs figma for presentations",
        "is the canva free version enough for a small business",
        "canva alternatives for professional design",
    ),
    products_or_services=(
        "graphic design",
        "presentation design",
        "social media design",
    ),
    use_cases=(
        "create marketing materials",
        "team collaboration",
        "brand templates",
    ),
    market_terms=("australia", "australian", "aud"),
)


_URBAN_COMPANY = GoldenOnboardingCase(
    slug="urban-company-india",
    brand_name="Urban Company",
    primary_market="India",
    website_url="https://www.urbancompany.com",
    sector="Consumer Services",
    category="at-home services booking marketplace",
    category_aliases=(
        "home services app",
        "at home salon booking",
        "home repair service app",
        "home cleaning service",
    ),
    business_model="local_service",
    # Coverage is national, but demand is expressed city by city: buyers type a
    # metro name or "near me", never a country.  This is the case that proves
    # locality has to be a facet rather than a row in an industry table.
    market_scope="local",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "book a trusted professional to come to my home",
        "get an appliance repaired quickly",
        "get a salon service without going to a salon",
        "know the price before booking",
    ),
    category_terms=(
        "salon at home",
        "home cleaning",
        "ac service and repair",
        "plumbing and electrical",
        "pest control",
        "appliance repair",
    ),
    expected_competitors=(
        "Housejoy",
        "NoBroker",
        "Yes Madam",
        "Zimmber",
        "Justdial",
    ),
    buyer_register="local_urgent",
    gold_buyer_prompts=(
        "salon at home service bangalore",
        "best home cleaning service near me",
        "ac servicing at home bangalore price",
        "trusted plumber near me bangalore",
        "how much does deep cleaning cost in mumbai",
        "at home spa service delhi",
        "electrician home visit charges bangalore",
        "best pest control service near me",
        "home painting service cost bangalore",
        "reliable carpenter near me hyderabad",
        "waxing at home service price delhi",
        "washing machine repair at home near me",
    ),
    gold_branded_prompts=(
        "is urban company reliable",
        "urban company vs local salon price",
        "urban company ac service review",
        "is urban company worth it for home cleaning",
        "urban company charges vs local plumber",
    ),
    products_or_services=(
        "at-home salon services",
        "home cleaning",
        "appliance repair",
    ),
    use_cases=("book a home service", "compare service prices", "urgent repair"),
    market_terms=("india", "indian", "inr"),
)


_JUPITER = GoldenOnboardingCase(
    slug="jupiter-india",
    brand_name="Jupiter",
    primary_market="India",
    website_url="https://jupiter.money",
    sector="Financial Services",
    category="digital banking app and neobank",
    category_aliases=(
        "neobank",
        "digital savings account",
        "banking app",
        "mobile banking app",
    ),
    business_model="regulated_finance",
    market_scope="national",
    buyer_type="b2c",
    # Deliberately weaker than the household names above: a mid-size fintech the
    # model knows partially, which is where over-confident invention shows up.
    knowledge_strength="weak",
    jobs_to_be_done=(
        "open a bank account without visiting a branch",
        "track spending automatically",
        "avoid minimum balance penalties",
        "know my money is safe and regulated",
    ),
    category_terms=(
        "digital savings account",
        "zero balance account",
        "upi payments",
        "spending insights",
        "neobank",
        "instant account opening",
    ),
    expected_competitors=(
        "Fi Money",
        "Niyo",
        "Slice",
        "Paytm Payments Bank",
        "Kotak 811",
    ),
    buyer_register="advice_seeking",
    gold_buyer_prompts=(
        "best digital banking app india",
        "zero balance savings account online india",
        "which banking app has the best user experience india",
        "best neobank in india",
        "digital savings account with high interest india",
        "app to track all my spending automatically india",
        "is it safe to use a neobank in india",
        "best account for salary with no minimum balance",
        "which bank app gives instant account opening",
        "upi app with the best rewards india",
        "how to open a savings account online without a branch visit",
        "digital bank with a free debit card india",
    ),
    gold_branded_prompts=(
        "is jupiter money safe",
        "jupiter vs fi money",
        "jupiter bank account review",
        "is jupiter a real bank or just an app",
        "jupiter money hidden charges",
    ),
    products_or_services=(
        "digital savings account",
        "spending insights",
        "upi payments",
    ),
    use_cases=("open an account", "track spending", "make payments"),
    market_terms=("india", "indian", "inr"),
)


_ZOHO = GoldenOnboardingCase(
    slug="zoho-india",
    brand_name="Zoho",
    primary_market="India",
    website_url="https://www.zoho.com",
    sector="Software",
    # The disambiguation case: Zoho sells 50+ products.  A generator that picks
    # one product, or that emits "business software" and stops, both fail.
    category="integrated business software suite for small and mid-size firms",
    category_aliases=(
        "business software suite",
        "crm software",
        "office software suite",
        "all in one business apps",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "run a whole business on one affordable software stack",
        "replace expensive per-seat enterprise software",
        "manage customers, invoices and email in one place",
        "avoid stitching together many separate tools",
    ),
    category_terms=(
        "crm software",
        "business email hosting",
        "accounting and invoicing",
        "helpdesk software",
        "hr and payroll software",
        "office productivity suite",
    ),
    expected_competitors=(
        "Salesforce",
        "HubSpot",
        "Freshworks",
        "Microsoft 365",
        "Google Workspace",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "affordable crm for small business",
        "all in one business software suite for smb",
        "cheap alternative to salesforce",
        "best crm for indian small business",
        "office suite alternative to microsoft 365",
        "integrated accounting and crm software",
        "best helpdesk software for small teams",
        "business email hosting with own domain cheap",
        "hr and payroll software for a small company india",
        "project management tool that integrates with crm",
        "business software that does not charge heavily per user",
        "best invoicing software for freelancers india",
    ),
    gold_branded_prompts=(
        "zoho vs salesforce for small business",
        "is zoho one worth it",
        "zoho crm vs hubspot pricing",
        "is zoho good enough for enterprise",
        "zoho mail vs google workspace",
    ),
    products_or_services=("crm software", "business email", "accounting software"),
    use_cases=("manage customers", "run business operations", "send invoices"),
    market_terms=("india", "indian", "inr"),
)


_VALTECH = GoldenOnboardingCase(
    slug="valtech-global",
    brand_name="Valtech",
    primary_market="Global",
    website_url="https://www.valtech.com",
    sector="Professional Services",
    category="digital commerce and experience implementation agency",
    category_aliases=(
        "digital transformation consultancy",
        "ecommerce implementation partner",
        "digital experience agency",
        "commerce systems integrator",
    ),
    business_model="professional_service",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="weak",
    jobs_to_be_done=(
        "replatform an ecommerce site without losing revenue",
        "find an implementation partner for a composable commerce build",
        "get a team that can deliver a digital product end to end",
        "modernise a legacy customer experience stack",
    ),
    category_terms=(
        "commerce replatforming",
        "composable commerce implementation",
        "digital experience delivery",
        "systems integration",
        "cx and design services",
        "data and analytics consulting",
    ),
    expected_competitors=(
        "Publicis Sapient",
        "Accenture Song",
        "Material",
        "Grid Dynamics",
        "Bounteous",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best agency for a commercetools implementation",
        "who can replatform our ecommerce site to composable commerce",
        "digital transformation consultancies for retail brands",
        "how do i choose an ecommerce implementation partner",
        "agencies that do sap commerce cloud migrations",
        "systems integrator for a headless commerce build",
        "which consultancy should we hire to rebuild our customer portal",
        "digital agency with in house engineering and design",
        "cost of hiring an agency to replatform an ecommerce site",
        "best digital experience agencies for enterprise clients",
        "who builds composable commerce for global brands",
        "agency vs in house team for an ecommerce rebuild",
    ),
    gold_branded_prompts=(
        "is valtech a good implementation partner",
        "valtech vs publicis sapient",
        "valtech ecommerce case studies",
        "valtech vs accenture song for commerce",
        "how much does valtech charge for a replatform",
    ),
    products_or_services=(
        "ecommerce implementation",
        "digital experience delivery",
        "data and analytics consulting",
    ),
    use_cases=(
        "replatform an ecommerce site",
        "hire an implementation partner",
        "modernise a digital experience",
    ),
    market_terms=("global", "worldwide", "international"),
)


SOFTWARE_AND_SERVICE_CASES: tuple[GoldenOnboardingCase, ...] = (
    _FEEDONOMICS,
    _CANVA,
    _URBAN_COMPANY,
    _JUPITER,
    _ZOHO,
    _VALTECH,
)
