"""The golden onboarding cases.

Split from :mod:`app.evaluations.onboarding_corpus` so the schema stays legible
next to a large hand-authored dataset. See that module for why each case is in
the corpus and how the facet vocabularies are used.
"""

from __future__ import annotations

from app.evaluations.onboarding_corpus import GoldenOnboardingCase

_FLIPKART = GoldenOnboardingCase(
    slug="flipkart-india",
    brand_name="Flipkart",
    primary_market="India",
    website_url="https://www.flipkart.com",
    sector="Retail and Ecommerce",
    category="general merchandise online marketplace",
    category_aliases=(
        "online shopping site",
        "ecommerce marketplace",
        "online store",
        "shopping app",
    ),
    business_model="marketplace",
    market_scope="national",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "buy a product online at the lowest price",
        "get fast and reliable delivery",
        "avoid counterfeit products",
        "pay in instalments",
    ),
    category_terms=(
        "online shopping",
        "mobile phones",
        "consumer electronics",
        "fashion and apparel",
        "home appliances",
        "cash on delivery",
    ),
    expected_competitors=(
        "Amazon India",
        "Meesho",
        "JioMart",
        "Myntra",
        "Tata CLiQ",
    ),
    buyer_register="terse_transactional",
    gold_buyer_prompts=(
        "best site to buy electronics online in india",
        "where to buy original branded shoes online india",
        "which online shopping app has fastest delivery in india",
        "cheapest place to buy iphone in india online",
        "safest online shopping site india for expensive items",
        "which ecommerce site has best return policy in india",
        "online shopping sites with cash on delivery india",
        "best online store for mobile phones with exchange offer",
        "where can i buy genuine products online without fakes india",
        "which shopping app gives the best discount during sale",
        "online marketplace with easy emi options india",
        "best site for buying home appliances online india",
    ),
    gold_branded_prompts=(
        "is flipkart or amazon better for electronics",
        "is flipkart reliable for buying phones",
        "flipkart vs meesho for cheap clothes",
        "does flipkart sell original products",
        "is flipkart big billion days actually worth it",
    ),
    products_or_services=("online shopping", "electronics", "fashion"),
    use_cases=("buy products online", "compare prices", "home delivery"),
    market_terms=("india", "indian", "inr"),
)

_BEST_AND_LESS = GoldenOnboardingCase(
    slug="best-less-australia",
    brand_name="Best&Less",
    primary_market="Australia",
    website_url="https://www.bestandless.com.au",
    sector="Retail and Ecommerce",
    category="value fashion and kids clothing retailer",
    category_aliases=(
        "budget clothing store",
        "affordable kids clothes",
        "discount fashion retailer",
        "cheap family clothing",
    ),
    business_model="retail",
    market_scope="national",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "clothe a family on a budget",
        "buy school uniforms cheaply",
        "replace kids clothes as they grow",
        "buy basic homewares affordably",
    ),
    category_terms=(
        "school uniforms",
        "kids clothing",
        "baby clothes",
        "womens basics",
        "homewares",
        "sleepwear",
    ),
    expected_competitors=(
        "Kmart Australia",
        "BIG W",
        "Target Australia",
        "Cotton On",
        "Bonds",
    ),
    buyer_register="terse_transactional",
    gold_buyer_prompts=(
        "cheap school uniforms australia",
        "where to buy affordable baby clothes australia",
        "best budget clothing stores australia",
        "cheapest place to buy kids clothes in australia",
        "affordable womens basics australia online",
        "good quality cheap towels and sheets australia",
        "where to buy school shoes cheap australia",
        "budget maternity clothes australia",
        "discount clothing stores near me australia",
        "best value pyjamas for kids australia",
        "cheap mens work clothes australia",
        "affordable homewares store australia",
    ),
    gold_branded_prompts=(
        "is best and less good quality",
        "best and less vs kmart for kids clothes",
        "does best and less have online shopping",
        "best and less school uniform review",
        "is best and less cheaper than target australia",
    ),
    products_or_services=("affordable clothing", "kids clothing", "homewares"),
    use_cases=("family essentials", "school clothes", "budget fashion"),
    market_terms=("australia", "australian", "aud"),
)

_FEEDONOMICS = GoldenOnboardingCase(
    slug="feedonomics-united-states",
    brand_name="Feedonomics",
    primary_market="United States",
    website_url="https://feedonomics.com",
    sector="Software",
    category="product feed management and marketplace syndication platform",
    category_aliases=(
        "feed management software",
        "product data syndication",
        "shopping feed tool",
        "feed optimization platform",
        "product feed management",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "list products on many marketplaces at once",
        "fix merchant centre disapprovals at scale",
        "optimise product data for shopping ads",
        "keep catalog data in sync across channels",
    ),
    category_terms=(
        "product feed management",
        "marketplace integrations",
        "catalog optimization",
        "google shopping feeds",
        "product data syndication",
        "feed automation",
    ),
    expected_competitors=(
        "Productsup",
        "Channable",
        "DataFeedWatch",
        "GoDataFeed",
        "Rithum",
        "Lengow",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best product feed management software for ecommerce",
        "how to sync shopify catalog to google shopping and amazon",
        "product feed management tools compared",
        "how do i fix google merchant center disapprovals at scale",
        "best way to list products on multiple marketplaces automatically",
        "product feed optimization tools for large catalogs",
        "software to manage product data across amazon walmart ebay",
        "enterprise feed management platform pricing",
        "how to automate product feeds for shopping ads",
        "tools that handle marketplace integrations for retailers",
        "what is a product feed management platform",
        "best feed tool for agencies managing multiple clients",
    ),
    gold_branded_prompts=(
        "feedonomics vs channable",
        "is feedonomics worth the price",
        "feedonomics alternatives",
        "feedonomics vs productsup for enterprise",
        "does feedonomics support walmart marketplace",
    ),
    products_or_services=(
        "product feed management",
        "marketplace integrations",
        "catalog optimization",
    ),
    use_cases=("sell on marketplaces", "shopping ads", "manage product data"),
    market_terms=("united states", "u.s.", "us market", "usa"),
)

_CANVA = GoldenOnboardingCase(
    slug="canva-australia",
    brand_name="Canva",
    primary_market="Australia",
    website_url="https://www.canva.com",
    sector="Software",
    category="browser-based graphic design and presentation tool",
    category_aliases=(
        "graphic design tool",
        "design software",
        "presentation maker",
        "social media design app",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="both",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "make professional-looking designs without design skills",
        "produce social media content quickly",
        "keep a team on-brand with shared templates",
        "build a presentation that looks good",
    ),
    category_terms=(
        "graphic design",
        "presentation design",
        "social media graphics",
        "brand templates",
        "logo design",
        "marketing collateral",
    ),
    expected_competitors=(
        "Adobe Express",
        "Microsoft Designer",
        "VistaCreate",
        "Figma",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "easiest graphic design tool for non designers",
        "best free tool to make social media posts",
        "how to make a presentation look professional without design skills",
        "best design app for small business marketing",
        "free alternative to photoshop for simple designs",
        "tool for making instagram posts with templates",
        "best software for shared team brand templates",
        "how to create a logo without hiring a designer",
        "design tool that works in the browser with no install",
        "best app for making flyers and posters",
        "cheap design software for nonprofits",
        "collaborative design tool for marketing teams",
    ),
    gold_branded_prompts=(
        "is canva pro worth it",
        "canva vs adobe express",
        "canva vs figma for presentations",
        "is the canva free version enough for a small business",
        "canva alternatives for professional design",
    ),
    products_or_services=(
        "graphic design",
        "presentation design",
        "social media design",
    ),
    use_cases=(
        "create marketing materials",
        "team collaboration",
        "brand templates",
    ),
    market_terms=("australia", "australian", "aud"),
)

_PUMA = GoldenOnboardingCase(
    slug="puma-india",
    brand_name="Puma",
    primary_market="India",
    website_url="https://in.puma.com",
    sector="Retail and Ecommerce",
    category="sportswear and athletic footwear brand",
    category_aliases=(
        "running shoes brand",
        "sports shoes",
        "athletic wear",
        "sneakers brand",
    ),
    business_model="d2c_product",
    market_scope="national",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "find running shoes that suit my gait and budget",
        "buy gym and training wear",
        "buy sneakers for everyday wear",
        "replace worn-out sports shoes",
    ),
    category_terms=(
        "running shoes",
        "sports shoes",
        "sneakers",
        "training wear",
        "athletic footwear",
        "track pants",
    ),
    expected_competitors=(
        "Adidas India",
        "Nike India",
        "Skechers India",
        "ASICS India",
        "New Balance India",
    ),
    buyer_register="terse_transactional",
    gold_buyer_prompts=(
        "best running shoes under 5000 india",
        "good sports shoes for gym india",
        "best sneakers for daily wear india",
        "comfortable running shoes for beginners india",
        "best athletic wear brands in india",
        "durable sports shoes for marathon training india",
        "best budget sports shoes for college students",
        "which brand has the best cushioning running shoes india",
        "sports shoes with good grip for treadmill",
        "best track pants for gym india",
        "affordable branded sneakers india online",
        "best shoes for flat feet running india",
    ),
    gold_branded_prompts=(
        "puma vs adidas running shoes india",
        "is puma good quality for running",
        "puma vs nike which is better value india",
        "are puma shoes worth the price",
        "puma running shoes review india",
    ),
    products_or_services=("sportswear", "running shoes", "athletic footwear"),
    use_cases=("running", "training", "everyday sneakers"),
    market_terms=("india", "indian", "inr"),
)

_URBAN_COMPANY = GoldenOnboardingCase(
    slug="urban-company-india",
    brand_name="Urban Company",
    primary_market="India",
    website_url="https://www.urbancompany.com",
    sector="Consumer Services",
    category="at-home services booking marketplace",
    category_aliases=(
        "home services app",
        "at home salon booking",
        "home repair service app",
        "home cleaning service",
    ),
    business_model="local_service",
    # Coverage is national, but demand is expressed city by city: buyers type a
    # metro name or "near me", never a country.  This is the case that proves
    # locality has to be a facet rather than a row in an industry table.
    market_scope="local",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "book a trusted professional to come to my home",
        "get an appliance repaired quickly",
        "get a salon service without going to a salon",
        "know the price before booking",
    ),
    category_terms=(
        "salon at home",
        "home cleaning",
        "ac service and repair",
        "plumbing and electrical",
        "pest control",
        "appliance repair",
    ),
    expected_competitors=(
        "Housejoy",
        "NoBroker",
        "Yes Madam",
        "Zimmber",
        "Justdial",
    ),
    buyer_register="local_urgent",
    gold_buyer_prompts=(
        "salon at home service bangalore",
        "best home cleaning service near me",
        "ac servicing at home bangalore price",
        "trusted plumber near me bangalore",
        "how much does deep cleaning cost in mumbai",
        "at home spa service delhi",
        "electrician home visit charges bangalore",
        "best pest control service near me",
        "home painting service cost bangalore",
        "reliable carpenter near me hyderabad",
        "waxing at home service price delhi",
        "washing machine repair at home near me",
    ),
    gold_branded_prompts=(
        "is urban company reliable",
        "urban company vs local salon price",
        "urban company ac service review",
        "is urban company worth it for home cleaning",
        "urban company charges vs local plumber",
    ),
    products_or_services=(
        "at-home salon services",
        "home cleaning",
        "appliance repair",
    ),
    use_cases=("book a home service", "compare service prices", "urgent repair"),
    market_terms=("india", "indian", "inr"),
)

_JUPITER = GoldenOnboardingCase(
    slug="jupiter-india",
    brand_name="Jupiter",
    primary_market="India",
    website_url="https://jupiter.money",
    sector="Financial Services",
    category="digital banking app and neobank",
    category_aliases=(
        "neobank",
        "digital savings account",
        "banking app",
        "mobile banking app",
    ),
    business_model="regulated_finance",
    market_scope="national",
    buyer_type="b2c",
    # Deliberately weaker than the household names above: a mid-size fintech the
    # model knows partially, which is where over-confident invention shows up.
    knowledge_strength="weak",
    jobs_to_be_done=(
        "open a bank account without visiting a branch",
        "track spending automatically",
        "avoid minimum balance penalties",
        "know my money is safe and regulated",
    ),
    category_terms=(
        "digital savings account",
        "zero balance account",
        "upi payments",
        "spending insights",
        "neobank",
        "instant account opening",
    ),
    expected_competitors=(
        "Fi Money",
        "Niyo",
        "Slice",
        "Paytm Payments Bank",
        "Kotak 811",
    ),
    buyer_register="advice_seeking",
    gold_buyer_prompts=(
        "best digital banking app india",
        "zero balance savings account online india",
        "which banking app has the best user experience india",
        "best neobank in india",
        "digital savings account with high interest india",
        "app to track all my spending automatically india",
        "is it safe to use a neobank in india",
        "best account for salary with no minimum balance",
        "which bank app gives instant account opening",
        "upi app with the best rewards india",
        "how to open a savings account online without a branch visit",
        "digital bank with a free debit card india",
    ),
    gold_branded_prompts=(
        "is jupiter money safe",
        "jupiter vs fi money",
        "jupiter bank account review",
        "is jupiter a real bank or just an app",
        "jupiter money hidden charges",
    ),
    products_or_services=(
        "digital savings account",
        "spending insights",
        "upi payments",
    ),
    use_cases=("open an account", "track spending", "make payments"),
    market_terms=("india", "indian", "inr"),
)

_ZOHO = GoldenOnboardingCase(
    slug="zoho-india",
    brand_name="Zoho",
    primary_market="India",
    website_url="https://www.zoho.com",
    sector="Software",
    # The disambiguation case: Zoho sells 50+ products.  A generator that picks
    # one product, or that emits "business software" and stops, both fail.
    category="integrated business software suite for small and mid-size firms",
    category_aliases=(
        "business software suite",
        "crm software",
        "office software suite",
        "all in one business apps",
    ),
    business_model="b2b_saas",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "run a whole business on one affordable software stack",
        "replace expensive per-seat enterprise software",
        "manage customers, invoices and email in one place",
        "avoid stitching together many separate tools",
    ),
    category_terms=(
        "crm software",
        "business email hosting",
        "accounting and invoicing",
        "helpdesk software",
        "hr and payroll software",
        "office productivity suite",
    ),
    expected_competitors=(
        "Salesforce",
        "HubSpot",
        "Freshworks",
        "Microsoft 365",
        "Google Workspace",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "affordable crm for small business",
        "all in one business software suite for smb",
        "cheap alternative to salesforce",
        "best crm for indian small business",
        "office suite alternative to microsoft 365",
        "integrated accounting and crm software",
        "best helpdesk software for small teams",
        "business email hosting with own domain cheap",
        "hr and payroll software for a small company india",
        "project management tool that integrates with crm",
        "business software that does not charge heavily per user",
        "best invoicing software for freelancers india",
    ),
    gold_branded_prompts=(
        "zoho vs salesforce for small business",
        "is zoho one worth it",
        "zoho crm vs hubspot pricing",
        "is zoho good enough for enterprise",
        "zoho mail vs google workspace",
    ),
    products_or_services=("crm software", "business email", "accounting software"),
    use_cases=("manage customers", "run business operations", "send invoices"),
    market_terms=("india", "indian", "inr"),
)

_GRAZA = GoldenOnboardingCase(
    slug="graza-united-states",
    brand_name="Graza",
    primary_market="United States",
    website_url="https://www.graza.co",
    sector="Food and Beverage",
    category="single-origin extra virgin olive oil brand",
    category_aliases=(
        "olive oil brand",
        "extra virgin olive oil",
        "cooking oil",
        "finishing oil",
    ),
    business_model="d2c_product",
    market_scope="national",
    buyer_type="b2c",
    # The small-brand case.  This is the vayudoot.in analogue: the model knows
    # little, so the profile must lean on site evidence and honestly report low
    # confidence rather than inventing a plausible-sounding business.
    knowledge_strength="weak",
    jobs_to_be_done=(
        "buy olive oil that is actually fresh and real",
        "have separate oils for cooking and finishing",
        "find a good gift for someone who cooks",
        "avoid adulterated supermarket olive oil",
    ),
    category_terms=(
        "extra virgin olive oil",
        "finishing olive oil",
        "cooking olive oil",
        "single origin olive oil",
        "harvest date olive oil",
        "squeeze bottle olive oil",
    ),
    expected_competitors=(
        "Brightland",
        "Kosterina",
        "California Olive Ranch",
        "Fat Gold",
        "Wonder Valley",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best olive oil for cooking and finishing",
        "good everyday olive oil brand",
        "best extra virgin olive oil for salad dressing",
        "which olive oil brands are actually real and not fake",
        "best olive oil in a squeeze bottle",
        "high quality olive oil for gifting",
        "single origin olive oil brands usa",
        "best olive oil for high heat cooking",
        "olive oil subscription usa",
        "fresh olive oil brands with a harvest date",
        "best tasting finishing olive oil",
        "affordable good olive oil that is not from the supermarket",
    ),
    gold_branded_prompts=(
        "is graza olive oil good",
        "graza drizzle vs sizzle",
        "graza olive oil review",
        "is graza worth the price",
        "graza vs brightland olive oil",
    ),
    products_or_services=(
        "extra virgin olive oil",
        "finishing olive oil",
        "cooking olive oil",
    ),
    use_cases=("everyday cooking", "finishing dishes", "gifting"),
    market_terms=("united states", "u.s.", "us market", "usa"),
)

_WAKEFIT = GoldenOnboardingCase(
    slug="wakefit-india",
    brand_name="Wakefit",
    primary_market="India",
    website_url="https://www.wakefit.co",
    sector="Retail and Ecommerce",
    category="direct-to-consumer mattress and home furniture brand",
    category_aliases=(
        "mattress brand",
        "memory foam mattress",
        "orthopedic mattress",
        "online mattress",
    ),
    business_model="d2c_product",
    market_scope="national",
    buyer_type="b2c",
    knowledge_strength="strong",
    jobs_to_be_done=(
        "fix back pain caused by a bad mattress",
        "buy a mattress online without lying on it first",
        "furnish a home affordably",
        "replace a sagging old mattress",
    ),
    category_terms=(
        "orthopedic mattress",
        "memory foam mattress",
        "queen size mattress",
        "bed frames",
        "study tables",
        "mattress trial period",
    ),
    expected_competitors=(
        "Sleepwell",
        "Duroflex",
        "Kurlon",
        "SleepyCat",
        "Pepperfry",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best mattress for back pain india under 20000",
        "memory foam vs spring mattress which is better",
        "best orthopedic mattress india",
        "which mattress is best for side sleepers india",
        "queen size mattress price india online",
        "best mattress brand india",
        "mattress with trial period india",
        "firm vs medium firm mattress for back pain",
        "best budget mattress india online",
        "how long does a foam mattress last",
        "best mattress for couples india",
        "affordable study table and chair online india",
    ),
    gold_branded_prompts=(
        "is wakefit mattress good",
        "wakefit vs sleepwell",
        "wakefit orthopedic memory foam review",
        "wakefit vs duroflex mattress",
        "is wakefit worth buying",
    ),
    products_or_services=("mattresses", "bed frames", "home furniture"),
    use_cases=("relieve back pain", "furnish a home", "buy a mattress online"),
    market_terms=("india", "indian", "inr"),
)

_BURROW = GoldenOnboardingCase(
    slug="burrow-united-states",
    brand_name="Burrow",
    primary_market="United States",
    website_url="https://burrow.com",
    sector="Retail and Ecommerce",
    category="modular direct-to-consumer sofa and furniture brand",
    category_aliases=(
        "modular sofa",
        "sectional couch",
        "direct to consumer furniture",
        "apartment furniture",
    ),
    business_model="d2c_product",
    market_scope="national",
    buyer_type="b2c",
    knowledge_strength="weak",
    jobs_to_be_done=(
        "get a sofa into a small apartment",
        "buy furniture that survives pets and kids",
        "assemble furniture without tools or help",
        "expand a couch later without replacing it",
    ),
    category_terms=(
        "modular sofa",
        "sectional couch",
        "sleeper sofa",
        "apartment furniture",
        "washable upholstery",
        "tool-free assembly",
    ),
    expected_competitors=(
        "Article",
        "Floyd",
        "Joybird",
        "Interior Define",
        "West Elm",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best modular sofa for a small apartment",
        "sectional couch that is easy to move",
        "best sofa for an apartment with a narrow doorway",
        "durable couch for pets and kids",
        "best direct to consumer furniture brands",
        "sofa you can assemble yourself without tools",
        "best washable couch cover sofa",
        "mid century modern sofa under 2000",
        "couch with fast shipping usa",
        "best sleeper sofa for guests in a small space",
        "modular couch you can add sections to later",
        "good quality sofa that ships in a box",
    ),
    gold_branded_prompts=(
        "is burrow furniture worth it",
        "burrow vs article sofa",
        "burrow sofa review durability",
        "burrow vs floyd couch",
        "is the burrow sofa comfortable",
    ),
    products_or_services=("modular sofas", "sectionals", "apartment furniture"),
    use_cases=("furnish a small space", "buy a durable couch", "easy assembly"),
    market_terms=("united states", "u.s.", "us market", "usa"),
)


# The corpus had eleven cases and not one service business, which is how a
# services firm shipped as a product vendor. Valtech is the shape that breaks:
# its site advertises the categories it WORKS IN ("commerce", "experience",
# "data"), so a careless read names the product category and then hands back the
# platforms Valtech implements -- Shopify Plus, SAP Commerce Cloud, commercetools
# -- as competitors. Every one of those scores high on substitutability, use-case
# overlap, geography and question visibility, so only a check on the *kind* of
# company rejects them. `expected_competitors` is therefore all agencies, and
# `unexpected` in the competitor evaluation is where that failure now shows up.
_VALTECH = GoldenOnboardingCase(
    slug="valtech-global",
    brand_name="Valtech",
    primary_market="Global",
    website_url="https://www.valtech.com",
    sector="Professional Services",
    category="digital commerce and experience implementation agency",
    category_aliases=(
        "digital transformation consultancy",
        "ecommerce implementation partner",
        "digital experience agency",
        "commerce systems integrator",
    ),
    business_model="professional_service",
    market_scope="global",
    buyer_type="b2b",
    knowledge_strength="weak",
    jobs_to_be_done=(
        "replatform an ecommerce site without losing revenue",
        "find an implementation partner for a composable commerce build",
        "get a team that can deliver a digital product end to end",
        "modernise a legacy customer experience stack",
    ),
    category_terms=(
        "commerce replatforming",
        "composable commerce implementation",
        "digital experience delivery",
        "systems integration",
        "cx and design services",
        "data and analytics consulting",
    ),
    expected_competitors=(
        "Publicis Sapient",
        "Accenture Song",
        "Material",
        "Grid Dynamics",
        "Bounteous",
    ),
    buyer_register="research_comparative",
    gold_buyer_prompts=(
        "best agency for a commercetools implementation",
        "who can replatform our ecommerce site to composable commerce",
        "digital transformation consultancies for retail brands",
        "how do i choose an ecommerce implementation partner",
        "agencies that do sap commerce cloud migrations",
        "systems integrator for a headless commerce build",
        "which consultancy should we hire to rebuild our customer portal",
        "digital agency with in house engineering and design",
        "cost of hiring an agency to replatform an ecommerce site",
        "best digital experience agencies for enterprise clients",
        "who builds composable commerce for global brands",
        "agency vs in house team for an ecommerce rebuild",
    ),
    gold_branded_prompts=(
        "is valtech a good implementation partner",
        "valtech vs publicis sapient",
        "valtech ecommerce case studies",
        "valtech vs accenture song for commerce",
        "how much does valtech charge for a replatform",
    ),
    products_or_services=(
        "ecommerce implementation",
        "digital experience delivery",
        "data and analytics consulting",
    ),
    use_cases=(
        "replatform an ecommerce site",
        "hire an implementation partner",
        "modernise a digital experience",
    ),
    market_terms=("global", "worldwide", "international"),
)


GOLDEN_ONBOARDING_CASES: tuple[GoldenOnboardingCase, ...] = (
    _FLIPKART,
    _BEST_AND_LESS,
    _FEEDONOMICS,
    _CANVA,
    _PUMA,
    _URBAN_COMPANY,
    _JUPITER,
    _ZOHO,
    _GRAZA,
    _WAKEFIT,
    _BURROW,
    _VALTECH,
)

# Same category, different geography and size.  A generator driven by a fixed
# industry table emits the same market prompts for both; the harness scores that
# collision directly rather than relying on inspection.
COLLISION_PAIR = ("wakefit-india", "burrow-united-states")

CASES_BY_SLUG: dict[str, GoldenOnboardingCase] = {
    case.slug: case for case in GOLDEN_ONBOARDING_CASES
}
